#TODO: we could use the proxy for monitoring purposes
services:
  # --- real first node (behind proxy) ---
  rethink1:
    image: rethinkdb:latest
    container_name: rethink1
     # spit data to /data/node1
     # tells everyone else that its chill that I am telling you the wrong address
    command: >
      rethinkdb --bind all
      --directory /data/node1
    volumes:
      - ./rethinkdb_data:/data # mount the data in /data/node1 back to local fs
    ports:
      - "28015:28015" # web UI forwarded
      - "8080:8080" # web UI forwarded
    networks:
      rnet:
        ipv4_address: 172.30.0.11

  # --- second node joins through proxy ---
  rethink2:
    image: rethinkdb:latest
    container_name: rethink2
    command: rethinkdb --bind all --directory /data/node2 --join rethink1:29015
    volumes:
      - ./rethinkdb_data:/data
    networks:
      rnet:
        ipv4_address: 172.30.0.12
    depends_on:
      - rethink1

  # --- third node joins through proxy ---
  rethink3:
    image: rethinkdb:latest
    container_name: rethink3
    command: rethinkdb --bind all --directory /data/node3 --join rethink1:29015
    volumes:
      - ./rethinkdb_data:/data
    networks:
      rnet:
        ipv4_address: 172.30.0.13
    depends_on:
      - rethink1

# configure docker bridge network
networks:
  rnet:
    driver: bridge
    driver_opts:
      com.docker.network.bridge.name: "rethink_bridge"

    ipam:
      config:
        - subnet: 172.30.0.0/16